title: Molart’s Blog about Xamarin
author: Molart
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I’ve started to learn Xamarin. I want to develop my coding skills
  and build awesome mobile applications. At the blog
  I will write about my journey across establishing new level of art to create
  great application for Android and iOS. You are welcome!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
